version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      astro:
        patterns:
          - "astro"
          - "@astrojs/*"
      eslint:
        patterns:
          - "eslint*"
          - "@typescript-eslint/*"
      tailwind:
        patterns:
          - "tailwindcss"
          - "@tailwindcss/*"
          - "autoprefixer"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
