name: Preview Deploy

on:
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened]
  pull_request_target:
    branches: [ main ]
    types: [closed]

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    environment: preview
    if: github.event_name == 'pull_request'

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npx astro build --config astro.config.preview.mjs
      env:
        PREVIEW_DOMAIN: preview${{ github.event.number }}.sjg.io

    - name: Create dynamic wrangler config
      run: |
        cat > wrangler.preview.json << EOF
        {
          "name": "sjg-io-preview-${{ github.event.number }}",
          "compatibility_date": "2025-01-08",
          "assets": {
            "directory": "./dist"
          },
          "routes": [
            {
              "pattern": "preview${{ github.event.number }}.sjg.io",
              "custom_domain": true
            }
          ]
        }
        EOF

    - name: Deploy Preview to Cloudflare Workers
      uses: cloudflare/wrangler-action@v3
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        wranglerVersion: '4'
        command: deploy --config wrangler.preview.json
      env:
        PREVIEW_DOMAIN: preview${{ github.event.number }}.sjg.io

    - name: Comment PR with preview URL
      uses: actions/github-script@v7
      with:
        script: |
          const previewUrl = `https://preview${{ github.event.number }}.sjg.io`;
          const comment = `🚀 **Preview deployed successfully!**
          
          **Preview URL:** ${previewUrl}
          
          This preview will be automatically cleaned up when the PR is merged or closed.`;
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: comment
          });

  cleanup-preview:
    runs-on: ubuntu-latest
    environment: preview
    if: github.event_name == 'pull_request_target' && (github.event.pull_request.merged == true || github.event.pull_request.state == 'closed')

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Create dynamic wrangler config for cleanup
      run: |
        cat > wrangler.preview.json << EOF
        {
          "name": "sjg-io-preview-${{ github.event.number }}",
          "compatibility_date": "2025-01-08",
          "assets": {
            "directory": "./dist"
          },
          "routes": [
            {
              "pattern": "preview${{ github.event.number }}.sjg.io",
              "custom_domain": true
            }
          ]
        }
        EOF

    - name: Delete Preview Deployment
      uses: cloudflare/wrangler-action@v3
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        wranglerVersion: '4'
        command: delete --config wrangler.preview.json --force
      env:
        PREVIEW_DOMAIN: preview${{ github.event.number }}.sjg.io

    - name: Comment PR about cleanup
      uses: actions/github-script@v7
      with:
        script: |
          const previewUrl = `https://preview${{ github.event.number }}.sjg.io`;
          const isMerged = `${{ github.event.pull_request.merged }}` === 'true';
          const action = isMerged ? 'merged' : 'closed';
          
          const comment = `🧹 **Preview site cleaned up**
          
          The preview site at ${previewUrl} has been automatically removed since this PR was ${action}.
          
          Thanks for using the preview system!`;
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: comment
          });
